### ISSUE TITLE
Error when running experiment using dataset from HOT-OSM

### ISSUE THREAD

**Issue by vrangayyan6** [devglobalpartners/ramp-code#3]
When using a dataset from HOT-OSM, I get error as below in second last code cell of [train_ramp_model_on_colab.ipynb]( #https://github.com/devglobalpartners/ramp-code/blob/main/colab/train_ramp_model_on_colab.ipynb).  
```
history = the_model.fit(train_batches, 
         epochs=n_epochs, 
         steps_per_epoch=steps_per_epoch, 
         validation_data=val_batches, 
         validation_steps=validation_steps,
         callbacks=callbacks_list)
``` 
---------------------------
OUTPUT --
```
 Epoch 1/2
 1/1 [==============================] - ETA: 0s - loss: nan - sparse_categorical_accuracy: 0.3680
 
 KeyErrorTraceback (most recent call last)
 <ipython-input-51-78c641e53f69> in <module>
       4         validation_data=val_batches,
       5         validation_steps=validation_steps,
 ----> 6         callbacks=callbacks_list)
 
 /usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
      65     except Exception as e:  # pylint: disable=broad-except
      66       filtered_tb = _process_traceback_frames(e.__traceback__)
 ---> 67       raise e.with_traceback(filtered_tb) from None
      68     finally:
      69       del filtered_tb
 
 /usr/local/lib/python3.7/dist-packages/keras/callbacks.py in _get_file_path(self, epoch, batch, logs)
    1486     except KeyError as e:
    1487       raise KeyError(
 -> 1488           f'Failed to format this callback filepath: "{self.filepath}". '
    1489           f'Reason: {e}')
    1490     self._write_filepath = distributed_file_utils.write_filepath(
 
 KeyError: 'Failed to format this callback filepath: "/content/drive/MyDrive/RAMP_HOME/ramp-data/TRAIN/HOTOSM/model-checkpts/20221014-000157/model_20221014-000157_{epoch:03d}_{val_sparse_categorical_accuracy:.3f}.tf". Reason: \'val_sparse_categorical_accuracy\''
```
Do you have any guidance on what I am doing wrong?

**Comment by cjohnstonconsulting** [comment]
Hi, 

I notice that in addition to the crashing error, you are getting nans for loss function values. This usually happens because something subtle is wrong with the training configuration. Can you attach the training configuration file you are using? 

That's likely where the crashing error is arising from as well.

**Comment by vrangayyan6** [comment]
Please find the training configuration below (don't see way to attach).  Thanks.

```
{
    "experiment_name":"HOT-OSM Efficient-Unet model",
    "discard_experiment":false,
    "logging":{
        "log_experiment":true,
        "experiment_log_path":"ramp-data/TRAIN/HOTOSM/HOTOSM-experiments.csv",
        "experiment_notes":"MULTICHANNEL model w/ earlystop, batchsize 16 on HOT-OSM dataset",
        "fields_to_log":[
            "experiment_name", 
            "experiment_notes", 
            "timestamp",
            "num_epochs",
            "batch_size",
            "output_img_shape",
            "input_img_shape",
            "get_loss_fn_name",
            "use_saved_model",
            "use_aug",
            "use_early_stopping",
            "use_clr",
            "random_seed",
            "num_classes",
            "get_optimizer_fn_name",
            "tb_logs_dir",
            "get_model_fn_name",
            "backbone",
            "train_img_dir",
            "train_mask_dir",
            "val_img_dir",
            "val_mask_dir"
        ]
    },
    "datasets":{
        "train_img_dir":"ramp-data/TRAIN/HOTOSM/chips",
        "train_mask_dir":"ramp-data/TRAIN/HOTOSM/multimasks",
        "val_img_dir":"ramp-data/TRAIN/HOTOSM/valchips",
        "val_mask_dir":"ramp-data/TRAIN/HOTOSM/val-multimasks"
    },
    "num_classes":4,
    "num_epochs":2,
    "batch_size":16,
    "input_img_shape":[256,256],
    "output_img_shape":[256,256],
    "loss":{
        "get_loss_fn_name":"get_sparse_categorical_crossentropy_fn",
        "loss_fn_parms":{}
    },
    "metrics":{
        "use_metrics":true,
        "get_metrics_fn_names":["get_sparse_categorical_accuracy_fn"],
        "metrics_fn_parms":[{}]
    },
    "optimizer":{
        "get_optimizer_fn_name":"get_adam_optimizer",
        "optimizer_fn_parms":{
            "learning_rate":3E-04
        }
    },
    "model":{
        "get_model_fn_name":"get_effunet_model",
        "model_fn_parms":{
            "backbone":"efficientnetb0",
            "classes":["background","buildings","boundary","close_contact"]
        }
    },
    "saved_model":{
        "use_saved_model":false
    },
    "augmentation":{
        "use_aug":true,

        "get_augmentation_fn_name":"get_augmentation_fn",
        "aug_list":["Rotate","ColorJitter"],
        "aug_parms":[
            {
                "border_mode":"BORDER_CONSTANT",
                "interpolation":"INTER_NEAREST",
                "value":[0.0,0.0,0.0],
                "mask_value":0,
                "p":0.7
            },
            {
                "p":0.7
            }
        ]
    },
    "early_stopping":{
        "use_early_stopping":false,
        "early_stopping_parms":{
            "monitor":"val_loss",
            "min_delta":0.005,
            "patience":50,
            "verbose":0,
            "mode":"auto",
            "restore_best_weights":false
        }
    },
    "cyclic_learning_scheduler":{
        "use_clr":false,
        "get_clr_callback_fn_name":"get_clr_callback_fn",
        "clr_callback_parms":{
            "mode":"triangular2",
            "stepsize":8,
            "max_lr":1e-4,
            "base_lr":3.25e-6
        },
        "clr_plot_dir":"ramp-data/TRAIN/HOTOSM/plots"
    },
    "tensorboard":{
        "use_tb":true,
        "tb_logs_dir":"ramp-data/TRAIN/HOTOSM/logs",
        "get_tb_callback_fn_name":"get_tb_callback_fn",
        "tb_callback_parms":{
            "histogram_freq":1,
            "update_freq":"batch"
        }
    },    
    "prediction_logging":{
        "use_prediction_logging":true,
        "get_prediction_logging_fn_name":"get_pred_logging_callback_fn"
    },
    "model_checkpts":{
        "use_model_checkpts":true,
        "model_checkpts_dir": "ramp-data/TRAIN/HOTOSM/model-checkpts",
        "get_model_checkpt_callback_fn_name":"get_model_checkpt_callback_fn",
        "model_checkpt_callback_parms":{
            "mode":"max",
            "save_best_only":true
        }
    },
    "random_seed":20220523
}
```

**Comment by vrangayyan6** [comment]
After preparing the data as per steps in https://rampml.global/data-preparation/, I get the error as below -

Epoch 1/2
1/1 [==============================] - ETA: 0s - loss: 1.8531 - sparse_categorical_accuracy: 0.1593KeyErrorTraceback (most recent call last)
<ipython-input-51-78c641e53f69> in <module>
      4         validation_data=val_batches,
      5         validation_steps=validation_steps,
----> 6         callbacks=callbacks_list)/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb/usr/local/lib/python3.7/dist-packages/keras/callbacks.py in _get_file_path(self, epoch, batch, logs)
   1486     except KeyError as e:
   1487       raise KeyError(
-> 1488           f'Failed to format this callback filepath: "{self.filepath}". '
   1489           f'Reason: {e}')
   1490     self._write_filepath = distributed_file_utils.write_filepath(KeyError: 'Failed to format this callback filepath: "/content/drive/MyDrive/RAMP_HOME/ramp-data/TRAIN/HOTOSM/model-checkpts/20221016-214207/model_20221016-214207_{epoch:03d}_{val_sparse_categorical_accuracy:.3f}.tf". Reason: \'val_sparse_categorical_accuracy\''

**Comment by cjohnstonconsulting** [comment]
Hi, 

First of all, your training configuration looks okay. 

I can see what the problem is (but I don't know the cause yet). You are at the end of your first training epoch, and your code wants to save the model to a file. The file is named with a name that includes the epoch number and the value (at the end of the epoch) of the validation sparse categorical accuracy. The cause of the crash is that the code is not finding a variable named 'val_sparse_categorical_accuracy', where it should be, in the 'logs' variable that gets passed to the _get_file_path function (the source code that's throwing the error is here: https://github.com/keras-team/keras/blob/bece2b30bc97534e42e742cc8242d3a9faebaaa2/keras/callbacks.py#L1586).

This is something that usually works, so I suspect the problem is with incompatible versions of the component libraries calling each other. Can you tell us if you set up your colab environment exactly according to the instructions, or whether there were any differences? Did anything unexpected happen during your setup? 

Please do the following. From the terminal in your colab environment, type 'pip freeze > pipfreeze.txt'. This will list all the versions of all the modules in your environment, and write them to a file called pipfreeze.txt. Save this file to your OneDrive, and then attach a copy here (you just have to drag and drop it into the editor window in github). Once we have it, on our side, we can compare it with a 'pipfreeze' file for a version that doesn't have this problem. Sorry for the hassle!

**Comment by vrangayyan6** [comment]
Thank you for your guidance.  In jupyter_lab_on_colab.ipynb, on executing 
`!pip install -q jupyterlab`
received following output -
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires tornado~=5.1.0, but you have tornado 6.2 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
```

Please find attached the files with commands and outputs in terminal (terminal_cmds_outputs.txt) and the pipfreeze.txt.
[terminal_cmds_outputs.txt](https://github.com/devglobalpartners/ramp-code/files/9815985/terminal_cmds_outputs.txt)

[pipfreeze.txt](https://github.com/devglobalpartners/ramp-code/files/9815990/pipfreeze.txt)

**Comment by vrangayyan6** [comment]
My team member found the problem was the batch size (it was 16 in the sample config) and i have fewer than 16 images for validation.  After changing batch size, the training ran successfully.  Thanks.
